[package]
name = "worlds_service"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
opentelemetry = "0.12.0"
opentelemetry-jaeger = "0.11.0"
tracing = { version = "0.1.25", features = ["log-always"] }
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-opentelemetry = "0.11.0"
tracing-subscriber = "0.2.17"
env_logger = "0.8.3"
dotenv = "0.15.0"
config = "0.11.0"
serde = {version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
actix-cors = "0.5.4"
actix-http = "2.2.0"
actix-service = "1.0.6"
actix-web = "3.3.2"
futures = "0.3.13"
actix-web-prom = "0.5.1"
prometheus = "0.11.0"
async-trait = "0.1.48"

[dev-dependencies]
assert2 = "0.3.5"
insta = "1.7.1"
